---
title: "R Notebook"
author: "Tu Tran and Andy Gubser"
date: \today
output: html_notebook
---

# Install and load packages

```{r, include=FALSE}
# install.packages("ggmap")
# install.packages("leaflet")
# install.packages("Hmisc")
# install.packages("geosphere")

#install the osmdata, sf, tidyverse and ggmap package
if(!require("osmdata")) install.packages("osmdata")
if(!require("tidyverse")) install.packages("tidyverse")
if(!require("sf")) install.packages("sf")
if(!require("ggmap")) install.packages("ggmap")

#load packages
library(tidyverse)
library(osmdata)
library(sf)
library(ggmap)
library("lubridate")
#library("leaflet")
library("Hmisc")
#library("geosphere")


```



# Load Data

```{r, include=FALSE}
setwd("./data")

d.bike.raw = read_csv("NYC-CitiBike-2016.csv")
colnames(d.bike.raw)
# describe(d.bike.raw)

```


# Preprocess Data

Convert Data to correct data type. Create a variable month that indicate the month of starttime. 

```{r, include=FALSE}

d.bike <- d.bike.raw %>% select_all(snakecase::to_snake_case)

d.bike <- d.bike %>%
  mutate(starttime = dmy_hms(starttime),
         stoptime = dmy_hms(stoptime),
         gender = factor(gender),
         start_station_id = factor(start_station_id),
         start_station_name = factor(start_station_name),
         end_station_id = factor(end_station_id),
         end_station_name = factor(end_station_name),
         bikeid = factor(bikeid),
         usertype = factor(usertype),
         birth_year = factor(birth_year),
         month = factor(month(starttime))
         )
head(d.bike)


                  #         distance = (start_station_longitude - end_station_latitude)^2 / (start_station_latitude - end_station_latitude)^2)
#        distance = distm(c(start_station_longitude, end_station_latitude), c(start_station_latitude, end_station_latitude), fun = distHaversine)

levels(d.bike$month)


```


Drop Outliers in coordinates
```{r}

start_plot <- ggplot() +
  geom_point(
    aes(x=start_station_latitude, y=start_station_longitude), data=d.bike)
# start_plot

end_plot <- ggplot() +
  geom_point(
    aes(x=end_station_latitude, y=end_station_longitude), data=d.bike)
# end_plot

d.bike <- filter(d.bike, 
                  start_station_latitude > 40.6,
                  end_station_latitude > 40.6
                  )

start_plot2 <- ggplot() +
  geom_point(
    aes(x=start_station_latitude, y=start_station_longitude), data=d.bike)
# start_plot2

end_plot2 <- ggplot() +
  geom_point(
    aes(x=end_station_latitude, y=end_station_longitude), data=d.bike)
# end_plot2
```



```{r}
#our background map
mad_map <- get_map(getbb("New York"),maptype = "toner-background", source="stamen")

#final map
ggmap(mad_map)+ 
    geom_leg(data=d.bike,
      color = "red", 
      alpha=0.01, 
      aes(
        x = start_station_longitude, 
        y = start_station_latitude, 
        xend = end_station_longitude, 
        yend = end_station_latitude
        )
      )+
  facet_grid(month) +
  labs(x="",y="")

levels(d.bike$month)


```














```{r}
library(ggmap)
# citation("ggmap")

ggmap(ggmap, source="osm") + 
  geom_leg(
    aes(x = start_station_longitude, 
        y = start_station_latitude, 
        xend = end_station_longitude, 
        yend = end_station_latitude,
        colour = "blue", alpha=0.0001
    )
  )


nyc_map <- fortify(gSimplify(nyc, 0.05))

gg <- ggplot()
gg <- gg + geom_map(data=nyc_map, map=nyc_map,
                    aes(x=long, y=lat, map_id=id),
                    color="black", fill="white", size=0.25)
gg <- gg + coord_equal() 
gg <- gg + theme_map()
gg



```


```{r}
colnames(d.bike)


```

















```{r}
# Set value for the minZoom and maxZoom settings.
leaflet(options = leafletOptions(minZoom = 0, maxZoom = 18))

m <- leaflet() %>%
  addTiles() %>%  # Add default OpenStreetMap map tiles
  addMarkers(lng=d.bike$start_station_longitude, 
             lat=d.bike$start_station_latitude, 
             popup="The birthplace of R")
m  # Print the map

```

d.bike




```{r}
ggplot() + 
  + geom_pi
  gender, d.bikes
```



```{r}
sessionInfo()
{miniCRAN} pkgDep()

```


# https://rstudio.github.io/leaflet/